name: Build Globed server

on:
  workflow_dispatch:
  push:

jobs:
  linux:
    name: Linux (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=game-server-linux-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=game-server-linux-${{ matrix.arch }}
          outputs: type=local,dest=out,compression=zstd,compression-level=8
          target: runtime-debian
          platforms: linux/${{ matrix.arch }}
          push: false
        env:
          DOCKER_BUILD_SUMMARY: false

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            cp out/game-server artifacts/game-server-x64
          else
            cp out/game-server artifacts/game-server-arm64
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: artifacts/*

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2025-12-01
          target: x86_64-pc-windows-msvc

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --release --features mimalloc --target x86_64-pc-windows-msvc
        env:
          SERVER_SHARED_PREBUILT_DATA: 1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: target/x86_64-pc-windows-msvc/release/game-server.exe

  merge:
    name: Merge artifacts
    runs-on: ubuntu-latest
    needs: [linux, windows]
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: game-server-build
          delete-merged: true
